In [1]:
import tensorflow as tf


In [26]:
tf.compat.v1.disable_eager_execution()

In [35]:
a = tf.constant("Hello")
b = tf.constant(" World")


In [36]:
# We can print or execute something in TENSORFLOW by creating Session in TF only
sess = tf.compat.v1.Session()

In [37]:
print(sess.run(a+b))

b'Hello World'


In [39]:
var1 = tf.constant(10)
var2 = tf.constant(20)

In [41]:
var1+var2

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [42]:
print(sess.run(var1+var2))

30


# Creating and running constants

In [139]:
# Make constant
const = tf.constant(10)

In [140]:
# Make a matrix
mat_1 = tf.fill((5,5),10) #tf.fill((rows, cols), values of all elements)

In [141]:
print(sess.run(mat_1))

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [142]:
zeros = tf.zeros((5,5))

In [143]:
print(sess.run(zeros)) # Matrix of zeros of 5X5

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [144]:
ones = tf.ones((5,5))

In [145]:
print(sess.run(ones)) # Matrix of ones of 5X5

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [146]:
randn = tf.random.normal((2,1), mean=10, stddev=0.5)

In [147]:
randu = tf.random.uniform((2,1), minval=0.4, maxval=0.5)

In [148]:
myops = [const, mat_1, zeros, ones, randn, randu]


In [149]:
for op in myops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[9.775337]
 [9.088469]]


[[0.4842152 ]
 [0.48848554]]




In [150]:
matrix1= tf.constant([[3,4,2]])

In [151]:
matrix1.get_shape()

TensorShape([1, 3])

In [152]:
matrix2 = tf.constant([[13, 9, 7, 15], [8,7,4,6], [6,4,0,3]])

In [153]:
matrix2.get_shape()

TensorShape([3, 4])

In [154]:
result = tf.matmul(matrix1, matrix2)

In [155]:
result

<tf.Tensor 'MatMul_1:0' shape=(1, 4) dtype=int32>

In [156]:
print(sess.run(result))

[[83 63 37 75]]


In [157]:
my_tensor = tf.random.uniform(shape=(2,2), minval=0, maxval=5)

In [158]:
sess.run(my_tensor)

array([[2.8814883, 2.2940993],
       [0.6102097, 1.586141 ]], dtype=float32)

# Creating Variables

In [159]:
# Create a Variable
var = tf.Variable(my_tensor)

In [160]:
print(var)

<tf.Variable 'Variable_1:0' shape=(2, 2) dtype=float32>


In [161]:
# But we will not be able to run this variable
# sess.run(var)

In [162]:
# Inorder to run or print a variable in tensorflow we
# have to first GLOABALLY INTIALIZE the variable with
# the help of globally initializer
init = tf.compat.v1.global_variables_initializer()

In [163]:
sess.run(init) # run the initializer

In [164]:
# Now we can run Variable
sess.run(var)

array([[4.2489805, 2.9075491],
       [4.649294 , 1.0630572]], dtype=float32)

# Creating Placeholders

In [167]:
# Placeholder are the kind of variables which can have variable size and shape of TF and can its values can be updated later.
pH1= tf.compat.v1.placeholder(dtype=tf.float32,shape=(2,1))

In [168]:
pH2 = tf.compat.v1.placeholder(dtype=tf.float32)